version: '3.8'

services:
  backend:
    image: syleedev/jungle-coders-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
