spring:
  profiles:
    active: profile

---

spring:
  config:
    activate:
      on-profile: local
jc:
  server:
    name: local

---

spring:
  config:
    activate:
      on-profile: test
jc:
  server:
    name: test


---

spring:
  config:
    activate:
      on-profile: prod

jc:
  server:
    name: prod-server

---

spring:
  config:
    activate:
      on-profile: dev
jc:
  server:
    name: dev-server